### PR TITLE
Spoof device option

### PR DESCRIPTION
**Pull request by Playez**
By default spoofs to unknown android with android version 8.1

### CODE REVIEW

**Comment by Playez** [comment]
Don't know, if i merged into the right branch, if i merged into wrong branch, tell me pls

**Comment by k1zn** [comment]
It would be nice if this spoof was added, for example, in the authorization window with custom parameters

**Comment by Playez** [comment]
> It would be nice if this spoof was added, for example, in the authorization window with custom parameters

I would try to do that, but i don't know if i could do that

**Comment by nikitasius** [comment]
Using hardcoded values will expose us like on the plate. You know, "Android unknown" it's probably Telegraher, lets ban it :)
I want to add text fields where you can overwrite these values.

By default it will be filled with legit values and you can just change the text inside and new values will be applied to **new registrations**.
For example: google pixel 1 is a vanilla. Google pixel XL is newone or whatever you want to add.

It will work for (the "MAIN" part):
* Build.MANUFACTURER
* Build.MODEL
* appVersion  - overwrite the app version if you want
* systemVersion - OS version
* systemLangCode / langCode - lang codes 
* installer - from default now hardcoded "com.android.vending"

It's possible to add more (the "BONUS" part):
* packageId - from default "org.telegram.messenger" to use any, but there are many places to replace it (referer in HTTP requests, contacts on phone etc)
* cFingerprint where is actually hardcodede vanilla fingerprint `49C1522548EBACD46CE322B6FD47F6092BB745D0F88082145CAF35E14DCC38E1`, place any from any app 
* API/HASH  - to use any api from any client.
But technically and logically most of folks will fuckup the session or expose themselves if i will add MAIN + BONUS. So guess the best is to add just "MAIN" part where you can rewrite most of data remaining a Telegraher working good as a vanilla.

**Comment by Bugaddr** [comment]
> Using hardcoded values will expose us like on the plate. You know, "Android unknown" it's probably Telegraher, lets ban it :) I want to add text fields where you can overwrite these values.
> 
> By default it will be filled with legit values and you can just change the text inside and new values will be applied to **new registrations**. For example: google pixel 1 is a vanilla. Google pixel XL is newone or whatever you want to add.
> 
> It will work for (the "MAIN" part):
> 
>     * Build.MANUFACTURER
> 
>     * Build.MODEL
> 
>     * appVersion  - overwrite the app version if you want
> 
>     * systemVersion - OS version
> 
>     * systemLangCode / langCode - lang codes
> 
>     * installer - from default now hardcoded "com.android.vending"
> 
> 
> It's possible to add more (the "BONUS" part):
> 
>     * packageId - from default "org.telegram.messenger" to use any, but there are many places to replace it (referer in HTTP requests, contacts on phone etc)
> 
>     * cFingerprint where is actually hardcodede vanilla fingerprint `49C1522548EBACD46CE322B6FD47F6092BB745D0F88082145CAF35E14DCC38E1`, place any from any app
> 
>     * API/HASH  - to use any api from any client.
>       But technically and logically most of folks will fuckup the session or expose themselves if i will add MAIN + BONUS. So guess the best is to add just "MAIN" part where you can rewrite most of data remaining a Telegraher working good as a vanilla.

I think you should make a new pr for this features.🙂 thanks for that.

**Comment by nikitasius** [comment]
added here 1dde8d965fd07d10157e33b2e9012a29556b4577 so i close this PR

**Pull request closed without merging**
